# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb4d7f9cef80d9d8857988fc315ac86ab1d2c7d9cfac3abd18262c24ddb9189275fae6e5c59823d282c496dd69e95d8130a7a3dcf5c0b9f1448ff568dc968466

test:
  secret_key_base: 3237099e90005e219275d638561f529a0287aba9606f428bded66bb26998b3b2638e5d3de2244b500892675530b87a690142690fc9fa926e143f2320fbbed50b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
